PRODUCT_MAKEFILES := $(LOCAL_DIR)/cypress.mk
PRODUCT_MAKEFILES += $(LOCAL_DIR)/cypressd.mk
PRODUCT_MAKEFILES += $(LOCAL_DIR)/cypressd_l.mk
PRODUCT_MAKEFILES += $(LOCAL_DIR)/cypress_nvi.mk
PRODUCT_MAKEFILES += $(LOCAL_DIR)/aosp_cypress.mk
